// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewspaperCMS.Models
{
    [Table("article")]
    public partial class article
    {
        public article()
        {
            category_names = new HashSet<category>();
        }

        [Key]
        public int id { get; set; }
        public int status { get; set; }
        //[DataType(DataType.DateTime, ErrorMessage = "Datatype must be datetime")]
        //[Column(TypeName = "date")]
        [DataType(DataType.Date)]
        public DateTime article_date { get; set; }

        [Required]
        [StringLength(120)]
        [Unicode(false)]
        public string title { get; set; }
        public string content { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string writer_id { get; set; }

        [ForeignKey("article_id")]
        [InverseProperty("articles")]
        public virtual ICollection<category> category_names { get; set; }
    }
}