// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewspaperCMS.Models
{
    [Table("category")]
    public partial class category
    {
        public category()
        {
            articles = new HashSet<article>();
        }

        public int id { get; set; }
        [Key]
        [StringLength(20)]
        [Unicode(false)]
        public string category_name { get; set; }

        [ForeignKey("category_name")]
        [InverseProperty("category_names")]
        public virtual ICollection<article> articles { get; set; }
    }
}